"""init tables

Revision ID: 6882b1280717
Revises: 
Create Date: 2025-11-04 12:23:53.854582

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6882b1280717'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_user_progress_user', table_name='user_progress')
    op.drop_index('idx_user_progress_word', table_name='user_progress')
    op.drop_constraint('user_progress_user_id_fkey', 'user_progress', type_='foreignkey')
    op.drop_constraint('user_progress_word_id_fkey', 'user_progress', type_='foreignkey')
    op.create_foreign_key(None, 'user_progress', 'users', ['user_id'], ['id'])
    op.create_foreign_key(None, 'user_progress', 'words', ['word_id'], ['id'])
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.drop_index('idx_word_text', table_name='words')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('idx_word_text', 'words', ['text'], unique=False)
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_constraint(None, 'user_progress', type_='foreignkey')
    op.drop_constraint(None, 'user_progress', type_='foreignkey')
    op.create_foreign_key('user_progress_word_id_fkey', 'user_progress', 'words', ['word_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key('user_progress_user_id_fkey', 'user_progress', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.create_index('idx_user_progress_word', 'user_progress', ['word_id'], unique=False)
    op.create_index('idx_user_progress_user', 'user_progress', ['user_id'], unique=False)
    # ### end Alembic commands ###
