"""add progress tracking columns

Revision ID: 79e9b7392f39
Revises: 6882b1280717
Create Date: 2025-11-08 18:52:59.488030

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '79e9b7392f39'
down_revision: Union[str, None] = '6882b1280717'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_level_words_id', table_name='level_words')
    op.drop_table('level_words')
    op.drop_index('ix_levels_id', table_name='levels')
    op.drop_table('levels')
    op.add_column('user_progress', sa.Column('attempts', sa.Integer(), nullable=True))
    op.add_column('user_progress', sa.Column('mastered', sa.String(), nullable=True))
    op.add_column('user_progress', sa.Column('last_attempt', sa.DateTime(), server_default=sa.text('now()'), nullable=True))
    op.add_column('user_progress', sa.Column('total_time', sa.Float(), nullable=True))
    op.alter_column('user_progress', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('user_progress', 'word_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('user_progress', 'score',
               existing_type=sa.INTEGER(),
               type_=sa.Float(),
               existing_nullable=True)
    op.create_index(op.f('ix_user_progress_id'), 'user_progress', ['id'], unique=False)
    op.alter_column('words', 'text',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.drop_constraint('words_text_key', 'words', type_='unique')
    op.create_index(op.f('ix_words_id'), 'words', ['id'], unique=False)
    op.create_index(op.f('ix_words_text'), 'words', ['text'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_words_text'), table_name='words')
    op.drop_index(op.f('ix_words_id'), table_name='words')
    op.create_unique_constraint('words_text_key', 'words', ['text'])
    op.alter_column('words', 'text',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.drop_index(op.f('ix_user_progress_id'), table_name='user_progress')
    op.alter_column('user_progress', 'score',
               existing_type=sa.Float(),
               type_=sa.INTEGER(),
               existing_nullable=True)
    op.alter_column('user_progress', 'word_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('user_progress', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_column('user_progress', 'total_time')
    op.drop_column('user_progress', 'last_attempt')
    op.drop_column('user_progress', 'mastered')
    op.drop_column('user_progress', 'attempts')
    op.create_table('levels',
    sa.Column('id', sa.INTEGER(), server_default=sa.text("nextval('levels_id_seq'::regclass)"), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='levels_pkey'),
    sa.UniqueConstraint('name', name='levels_name_key'),
    postgresql_ignore_search_path=False
    )
    op.create_index('ix_levels_id', 'levels', ['id'], unique=False)
    op.create_table('level_words',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('level_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('word_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['level_id'], ['levels.id'], name='level_words_level_id_fkey'),
    sa.ForeignKeyConstraint(['word_id'], ['words.id'], name='level_words_word_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='level_words_pkey'),
    sa.UniqueConstraint('level_id', 'word_id', name='unique_level_word')
    )
    op.create_index('ix_level_words_id', 'level_words', ['id'], unique=False)
    # ### end Alembic commands ###
